-- MySQL Script generated by MySQL Workbench
-- Mon Nov 17 08:17:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema library_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library_system` DEFAULT CHARACTER SET utf8 ;
USE `library_system` ;

-- -----------------------------------------------------
-- Table `library_system`.`languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_system`.`languages` (
  `lid` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'A nyelv azonosítója',
  `language` VARCHAR(45) NOT NULL COMMENT 'A nyelv megnezevése',
  PRIMARY KEY (`lid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_system`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_system`.`users` (
  `uid` INT NOT NULL AUTO_INCREMENT COMMENT 'A felhasználó tábla azonosítója',
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL COMMENT 'A felhasználó email címe',
  `password` VARCHAR(60) NOT NULL COMMENT 'A felhasználó jelszava',
  `role` VARCHAR(45) NOT NULL DEFAULT 'member' COMMENT 'A felhasználó jogosultságiköre',
  `mobile` VARCHAR(45) NULL COMMENT 'A felhasználó mobiltelefonszáma',
  `address` VARCHAR(255) NOT NULL COMMENT 'A felhasználó levelezési címe',
  `idnumber` VARCHAR(25) NOT NULL COMMENT 'A felhasználó személyi igazolvány száma',
  `is_active` TINYINT NOT NULL DEFAULT 0 COMMENT 'A felhasználó státusza:  \n0 - inaktív\n1 - aktív\n2 - törölt',
  `regtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'A regisztráció időpontja',
  `updated_at` TIMESTAMP NOT NULL COMMENT 'A rekord utolsó módosításának időpontja',
  `languages_lid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `idnumber_UNIQUE` (`idnumber` ASC) VISIBLE,
  INDEX `fk_users_languages1_idx` (`languages_lid` ASC) VISIBLE,
  CONSTRAINT `fk_users_languages1`
    FOREIGN KEY (`languages_lid`)
    REFERENCES `library_system`.`languages` (`lid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_system`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_system`.`authors` (
  `aid` INT NOT NULL AUTO_INCREMENT COMMENT 'A szerző azonosítója',
  `firstname` VARCHAR(255) NOT NULL COMMENT 'A szerző nevének első része',
  `lastname` VARCHAR(255) NULL COMMENT 'A szerző nevének utolsó része',
  `birth_date` DATE NOT NULL COMMENT 'A szerző születési dátuma',
  `death_date` DATE NULL,
  `nationality` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`aid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_system`.`publishers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_system`.`publishers` (
  `pid` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'A kiadó azonosítója',
  `name` VARCHAR(255) NOT NULL COMMENT 'A kiadó neve',
  `email` VARCHAR(255) NOT NULL COMMENT 'A kiadó email címe',
  `address` VARCHAR(255) NOT NULL COMMENT 'A kiadó publikus címe',
  `phone` VARCHAR(45) NOT NULL COMMENT 'A kiadó publikus telefonszáma',
  `website` VARCHAR(255) NULL COMMENT 'A kiadó weboldala',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'A kiadó felvételének dátuma',
  `updated_at` TIMESTAMP NULL COMMENT 'A kiadó adatainak utolsó módosításának dátuma',
  PRIMARY KEY (`pid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_system`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_system`.`categories` (
  `cid` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'A kategória azonosítója',
  `name` VARCHAR(255) NOT NULL COMMENT 'A kategória elnevezése',
  `description` TEXT NOT NULL COMMENT 'A kategória leírása',
  `parent_id` INT UNSIGNED NULL COMMENT 'Visszacsatolási azonosító',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Rekord létrehozásának időpontja',
  `updated_at` TIMESTAMP NULL COMMENT 'Rekord frissítésének időpontja',
  PRIMARY KEY (`cid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_system`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_system`.`books` (
  `bid` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Könyv azonosítója',
  `isbn` VARCHAR(255) NOT NULL COMMENT 'Könyv ISBN száma',
  `title` VARCHAR(255) NOT NULL COMMENT 'Könyv címe',
  `subtitle` VARCHAR(255) NULL COMMENT 'Könyv alcíme',
  `pagenumber` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'A könyv oldalainak száma',
  `edition` VARCHAR(10) NOT NULL,
  `publication_year` YEAR NOT NULL,
  `lid` INT UNSIGNED NOT NULL COMMENT 'Idegen kulcs',
  `users_uid` INT NOT NULL,
  `publishers_pid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`bid`, `publishers_pid`),
  INDEX `fk_books_languages_idx` (`lid` ASC) VISIBLE,
  INDEX `fk_books_users1_idx` (`users_uid` ASC) VISIBLE,
  INDEX `fk_books_publishers1_idx` (`publishers_pid` ASC) VISIBLE,
  CONSTRAINT `fk_books_languages`
    FOREIGN KEY (`lid`)
    REFERENCES `library_system`.`languages` (`lid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_users1`
    FOREIGN KEY (`users_uid`)
    REFERENCES `library_system`.`users` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_publishers1`
    FOREIGN KEY (`publishers_pid`)
    REFERENCES `library_system`.`publishers` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_system`.`books_has_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_system`.`books_has_categories` (
  `books_bid` INT UNSIGNED NOT NULL,
  `categories_cid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`books_bid`, `categories_cid`),
  INDEX `fk_books_has_categories_categories1_idx` (`categories_cid` ASC) VISIBLE,
  INDEX `fk_books_has_categories_books1_idx` (`books_bid` ASC) VISIBLE,
  CONSTRAINT `fk_books_has_categories_books1`
    FOREIGN KEY (`books_bid`)
    REFERENCES `library_system`.`books` (`bid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_has_categories_categories1`
    FOREIGN KEY (`categories_cid`)
    REFERENCES `library_system`.`categories` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_system`.`books_has_authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_system`.`books_has_authors` (
  `books_bid` INT UNSIGNED NOT NULL,
  `authors_aid` INT NOT NULL,
  PRIMARY KEY (`books_bid`, `authors_aid`),
  INDEX `fk_books_has_authors_authors1_idx` (`authors_aid` ASC) VISIBLE,
  INDEX `fk_books_has_authors_books1_idx` (`books_bid` ASC) VISIBLE,
  CONSTRAINT `fk_books_has_authors_books1`
    FOREIGN KEY (`books_bid`)
    REFERENCES `library_system`.`books` (`bid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_has_authors_authors1`
    FOREIGN KEY (`authors_aid`)
    REFERENCES `library_system`.`authors` (`aid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_system`.`bookcopies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_system`.`bookcopies` (
  `bcid` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'A könyv példányának azonosítója',
  `acquisition_date` DATE NOT NULL COMMENT 'A könyv példányának beszerzési dátuma',
  `price` INT NOT NULL DEFAULT 0 COMMENT 'A könyv példányának ára',
  `condition` VARCHAR(100) NOT NULL DEFAULT 'Kitűnő' COMMENT 'A könyv példányának állapota',
  `status` VARCHAR(45) NOT NULL DEFAULT 'kölcsönözhető' COMMENT 'A könyv státusza',
  `comment` TEXT NULL COMMENT 'megjegyzés',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL,
  `books_bid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`bcid`, `books_bid`),
  INDEX `fk_book_copies_books1_idx` (`books_bid` ASC) VISIBLE,
  CONSTRAINT `fk_book_copies_books1`
    FOREIGN KEY (`books_bid`)
    REFERENCES `library_system`.`books` (`bid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_system`.`loans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_system`.`loans` (
  `lid` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'A kölcsönzés azonosítója',
  `loan_date` DATE NOT NULL COMMENT 'A kölcsönzés dátuma',
  `due_date` DATE NOT NULL COMMENT 'A kölcsönzés végenek tervezett időpontja',
  `return_date` DATE NULL COMMENT 'A visszahozás tényleges dátuma ',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`lid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_system`.`bookcopies_has_loans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_system`.`bookcopies_has_loans` (
  `bookcopies_bcid` INT UNSIGNED NOT NULL,
  `bookcopies_books_bid` INT UNSIGNED NOT NULL,
  `loans_lid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`bookcopies_bcid`, `bookcopies_books_bid`, `loans_lid`),
  INDEX `fk_bookcopies_has_loans_loans1_idx` (`loans_lid` ASC) VISIBLE,
  INDEX `fk_bookcopies_has_loans_bookcopies1_idx` (`bookcopies_bcid` ASC, `bookcopies_books_bid` ASC) VISIBLE,
  CONSTRAINT `fk_bookcopies_has_loans_bookcopies1`
    FOREIGN KEY (`bookcopies_bcid` , `bookcopies_books_bid`)
    REFERENCES `library_system`.`bookcopies` (`bcid` , `books_bid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookcopies_has_loans_loans1`
    FOREIGN KEY (`loans_lid`)
    REFERENCES `library_system`.`loans` (`lid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
